FROM node:16.20.2-slim
WORKDIR /app

ENV REACT_APP_API_ENDPOINT $REACT_APP_API_ENDPOINT
ENV REACT_APP_GEOJSON_ENDPOINT $REACT_APP_GEOJSON_ENDPOINT
ENV REACT_APP_MAPBOX_TOKEN $REACT_APP_MAPBOX_TOKEN
ENV REACT_APP_MAPBOX_STYLE $REACT_APP_MAPBOX_STYLE

COPY . .

RUN yarn install

EXPOSE 3000

CMD ["yarn", "start"]